FROM fedora:30

LABEL maintainer "Brian Stinson <brian@bstinson.com>"

RUN dnf -y install python3-tox krb5-devel popt-devel python3-devel rpm-devel @c-development git

RUN chown -R 1001:0 $HOME && \
    chmod -R g+rw $HOME

USER 1001
